# Generated by Django 2.1.7 on 2019-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT_NAME', models.CharField(max_length=50)),
                ('HOMEPAGE', models.URLField(max_length=100)),
            ],
        ),
    ]
